language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: fnMo35B9FamiAou5yLuW41EujiMxPWW0YkqsBtxd+OaW3b4XRu5fQHc9//+V2C5YU8jbNMNTVzIbUT9/4JpkQ1mAdbHOK0r2/R4o+dOASDV/s8BMO+hCBm3X33joFC4W2ui3QuRn59YIEN/WkagFBQ8E1DM5Qk92z0xkbmWpSPsHV8OlzUgmq3OODxB6SVE1EAgVvSCSsgPi+Qzv93df9zVwbDxzhZN6kCJ4MD631J7ZCFGOSIPBUE9fQEIKFnQMdqPXXJI8oD2pzrGS0YNa1usFU5RkswYad0vJawdu0914Jhr8JMGn6kfh6+jC74hOLz1BldHkaISh9zsroNDDvmVF+yH6LcUbvR/nG/RA6pjq+kIeyAHtTuycz06PfqVJwPUI/rl+6VHAaYUpTc4aiwMnC+SGtYoL7cP62fmml/Ue8Hfm88NcsmQUDIPWQiwsrzS7QwB5aw52eShBecPoCEiAW7mRIeTAqAPh1dN7LEZFuBiFt8z6kO7Oweg5bAK2/QyfZeGfs+r45KwRAdaI0Pwk8dOuPtTVAJUVkSQIIQxxQruOW2MeC1zAVzGTn78ZggwcHVLA4CEeiE5MAuVrJYTbHHTzcuRKeZYZwEJmxrllpkVFzL9PPR2r4aQrywMOOGwE8HiK1hA235g/gTqAY3bPbhGDat2ksNXEpwvJa6s=
  app:
    master: superta
    development: superta-dev
