language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: eGvFqRkxeB7YHm3HcDzbKYgdNCsUYbe8ipVy7I2raBsmzp1FFqVT6JX/78Wlxm/lsa1doczadw7g6y+ztqneO+nuCp5l3P8m/GQ9D1/Gmz0eqqZE0eLdMyLARUqRh2BmwI2/Otinr7DYIq9VazX/W+WFUzIVW9XemlUAaq4GP4oUS4f6U+sjaaaPRuzfAGSsospjmwPB91taka3rWnrngDN1K026sVQgCe/48crF4s+uSf8dpC6h7TMfG0gTtZXp59K7H/LgGWp0LYquJpX0uhMFxrPZmf8sorR4IsQocw/hD5WKfsZ+ICICNIdLOTrY321UGoS9LSOFSg2J63PRXgfO4Mj0I0nQryDXZ5CjGHbCnsiWgy/6ozepn02CmnyCEqxZZ5Kgp307PZmxOKxjrcMf+oyQ0QzldC/mSJR4rp9CQmT+eWgUNDRka5bU8K31BrTHQ/FLR9G0CQ5ap9p9aO1hXldB5ImAUQ2OjeBf0PiaIwEhS3V9GinDMLD73JzAAhBAUorTBcFN2C7XvMTOvrkJCe6S+6MzIezSYKMFakAQKX93FdMjwYMLUn9YUocxujt09jSqb6BUPr+AGSM/6UeG2FbB06Xo4AckeFLI1+njvttkBLlhWv7oIRMW70nwksjpFW1C7LrsdnkrOoEooNUmUsnJNMFkhScu2coGeQk=
  app:
    master: superta
    development: superta-dev
