language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GBws2qMaDU8xaX2gcSUcNe0/iAIQoDWGez/IPgtmp5Iy3odywDKGH5P/xY6H0XnzxENH9WYGVtC5bUX50B+9vp637EBWG03jyzv+lvtQI6w00lA2y/nb23FXzCwxn0atcwbh9sp+8jNQ7/Z3+SQgIxelWwrsrtVfZSV6iHsrUyCnlWqKkx62gszGuMV3vImhTs5FlKbYEff7YxqCqYnS0SFqhJPraCM1ETdmiuTuxVukQWjlPsafKcicRrtpEAcKUP+1Qk/x2GkzxkeF5/4LP8XWH8O/ZF89nzGVzdijkp1lWbgd8Cd91A9bf/kdYSzSUPP0CS+d9GLD06ke9tgAXrOdxXaVTWnRMcPRxpHFzeQMumtF0ZijaQS81u3tZGPCfiO4DJguV6v4yrrnZRsvooXhIFJP8FuhbKpHWtoKzbgtU1JpECMizGul90q8C7tWF0l7NvKTYKS6xMitct+CJoue8jffYzZkFaVPMM9ZJ6fRDankQYfraXi/p4zvdUvjDMHlrNZst8oTyVv6RIksYOFWYtFuh2f4EnIr98EwOFRBHeLjuQRxPzEnyZKVFwaKWy65oSkf+rutHcytyIxyWjTDfTChuaOj6NCNC5GeM3e6OvxZU5o71iSa2k9g8ZXTLTsMGL07cbaO7JsDEqhZUCx08LVWC2gAjPneKkrqf1c=
  app:
    master: superta
    development: superta-dev
