language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: cm+ziXHvoTNRqxds1eifsf6oziuxFmX6KNLpozCXwpsXdmUTsPxkPI9pZTZfioxIgwFJtPr4TWDt+crvYhPL9S+bzcJaiwwRmNwR0fRtpvxU+HgsSD24dNijFmdqdCZg2dPc/PtYxLucSS09viY+5a2q8aUyKUFx8K8oxI6IUJeNCzwT0t/NquQHYRsAbyvvT3SMECISIl/Q6XvCCJp/pJdSgKZqFmY8L+84YzUxl5x5uIzU7NtwprgBmWHMGZYeGbR/ZunZPASzDuJ0vOGDPF+tfR46Bimm2VEVgbwtxcRxR9jGAuRIX/7SAuYsmAR9QArqzTYi/qXWjTEPtkxY7vEXcaliSKBKYLf+T298qJigj0l+ZWLIcv6rt/sjPl/Bkb22TPx8o0CSziIoHCdliw3qZCTlsG0rn2cpN1H9urzXCfZPegTlcxkiCW+K09L8HtDriOhh57mMuiexZaS8JqhiBvEWwK12L9J0w3jbUCKw6xoqkU2ud5wu7AQfzYXaUfikXiF3AP+Y4XP48wkkKMccSrpbdJ7BC2AdF9dbzfTBCmoPECD+yfgH4JiOZQAQnsDr/+Y5xhzUwHKZS8KKmuwpU5Eb8pUR/SxbEwskEHGUajjSBZS0gUVh3FaTwn5ovjS5xLfe/2xav03GVjLW5H5q+ZQYPhE07wwJ6BMzG5U=
  app:
    master: superta
    development: superta-dev
